/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../ClientApp/app/client/client-routing.module';
import * as i2 from '@angular/router';
export const ClientRoutingModuleNgFactory:i0.NgModuleFactory<i1.ClientRoutingModule> = i0.ɵcmf(i1.ClientRoutingModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(512,
          i2.RouterModule,i2.RouterModule,[[2,i2.ɵa],[2,i2.Router]]),i0.ɵmpd(512,i1.ClientRoutingModule,
          i1.ClientRoutingModule,([] as any[])),i0.ɵmpd(1024,i2.ROUTES,() => {
        return [[{path:'internal',loadChildren:'./internal/client.internal.module#ClientInternalModule'},
            {path:'public',loadChildren:'./public/client.public.module#ClientPublicModule'}]];
      },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvVmlsbWFudGFzL0RvY3VtZW50cy9WaXN1YWwgU3R1ZGlvIDIwMTcvUHJvamVjdHMvQW5ndWxhcjJDb3JlVGVtcGxhdGUvc3JjL1RlbXBsYXRlLkNsaWVudC9DbGllbnRBcHAvYXBwL2NsaWVudC9jbGllbnQtcm91dGluZy5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvVmlsbWFudGFzL0RvY3VtZW50cy9WaXN1YWwgU3R1ZGlvIDIwMTcvUHJvamVjdHMvQW5ndWxhcjJDb3JlVGVtcGxhdGUvc3JjL1RlbXBsYXRlLkNsaWVudC9DbGllbnRBcHAvYXBwL2NsaWVudC9jbGllbnQtcm91dGluZy5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
