/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../ClientApp/app/admin/admin.module';
import * as i2 from './internal/admin.internal.component.ngfactory';
import * as i3 from './public/login/login.component.ngfactory';
import * as i4 from './internal/users/users.component.ngfactory';
import * as i5 from './internal/products/products.component.ngfactory';
import * as i6 from '@angular/forms';
import * as i7 from '@angular/common';
import * as i8 from '../../../../ClientApp/app/admin/internal/users/users.service';
import * as i9 from '../../../../ClientApp/app/admin/internal/users/users-resolver';
import * as i10 from '../../../../ClientApp/app/admin/internal/products/products.service';
import * as i11 from '../../../../ClientApp/app/admin/internal/products/products-resolver';
import * as i12 from '@angular/router';
import * as i13 from '../../../../ClientApp/app/admin/admin-routing.module';
import * as i14 from '../../../../ClientApp/app/admin/public/admin.public.module';
import * as i15 from '../../../../ClientApp/app/admin/internal/admin.internal.module';
import * as i16 from '../../../../ClientApp/app/admin/internal/admin.internal.component';
import * as i17 from '../../../../ClientApp/app/admin/public/login/login.component';
import * as i18 from '../../../../ClientApp/app/admin/internal/users/users.component';
import * as i19 from '../../../../ClientApp/app/admin/internal/products/products.component';
export const AdminModuleNgFactory:i0.NgModuleFactory<i1.AdminModule> = i0.ɵcmf(i1.AdminModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.AdminInternalComponentNgFactory,i3.AdminLoginComponentNgFactory,
              i4.UserComponentNgFactory,i5.ProductComponentNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(4608,i6.ɵi,i6.ɵi,([] as any[])),i0.ɵmpd(4608,
          i6.FormBuilder,i6.FormBuilder,([] as any[])),i0.ɵmpd(4608,i7.NgLocalization,
          i7.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,i8.UserService,i8.UserService,
          ([] as any[])),i0.ɵmpd(4608,i9.UsersResolver,i9.UsersResolver,[i8.UserService]),
          i0.ɵmpd(4608,i10.ProductService,i10.ProductService,([] as any[])),i0.ɵmpd(4608,
              i11.ProductsResolver,i11.ProductsResolver,[i10.ProductService]),i0.ɵmpd(512,
              i12.RouterModule,i12.RouterModule,[[2,i12.ɵa],[2,i12.Router]]),i0.ɵmpd(512,
              i13.AdminRoutingModule,i13.AdminRoutingModule,([] as any[])),i0.ɵmpd(512,
              i6.ɵba,i6.ɵba,([] as any[])),i0.ɵmpd(512,i6.FormsModule,i6.FormsModule,
              ([] as any[])),i0.ɵmpd(512,i6.ReactiveFormsModule,i6.ReactiveFormsModule,
              ([] as any[])),i0.ɵmpd(512,i14.AdminPublicModule,i14.AdminPublicModule,
              ([] as any[])),i0.ɵmpd(512,i7.CommonModule,i7.CommonModule,([] as any[])),
          i0.ɵmpd(512,i15.AdminInternalModule,i15.AdminInternalModule,([] as any[])),
          i0.ɵmpd(512,i1.AdminModule,i1.AdminModule,([] as any[])),i0.ɵmpd(1024,i12.ROUTES,
              () => {
                return [[{path:'internal',component:i16.AdminInternalComponent,loadChildren:'./internal/admin.internal.module#AdminInternalModule'},
                    {path:'public',loadChildren:'./public/admin.public.module#AdminPublicModule'}],
                    [{path:'login',component:i17.AdminLoginComponent}],[{path:'users',
                        component:i18.UserComponent,resolve:{users:i9.UsersResolver}},
                        {path:'products',component:i19.ProductComponent,resolve:{products:i11.ProductsResolver}}]];
              },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvVmlsbWFudGFzL0RvY3VtZW50cy9WaXN1YWwgU3R1ZGlvIDIwMTcvUHJvamVjdHMvQW5ndWxhcjJDb3JlVGVtcGxhdGUvc3JjL1RlbXBsYXRlLkNsaWVudC9DbGllbnRBcHAvYXBwL2FkbWluL2FkbWluLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9WaWxtYW50YXMvRG9jdW1lbnRzL1Zpc3VhbCBTdHVkaW8gMjAxNy9Qcm9qZWN0cy9Bbmd1bGFyMkNvcmVUZW1wbGF0ZS9zcmMvVGVtcGxhdGUuQ2xpZW50L0NsaWVudEFwcC9hcHAvYWRtaW4vYWRtaW4ubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
