/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '@angular/router';
import * as i2 from '../../../ClientApp/app/application.component';
const styles_ApplicationComponent:any[] = ([] as any[]);
export const RenderType_ApplicationComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_ApplicationComponent,data:{}});
export function View_ApplicationComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(16777216,(null as any),(null as any),1,'router-outlet',
      ([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
      i0.ɵdid(212992,(null as any),0,i1.RouterOutlet,[i1.ChildrenOutletContexts,i0.ViewContainerRef,
          i0.ComponentFactoryResolver,[8,(null as any)],i0.ChangeDetectorRef],(null as any),
          (null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export function View_ApplicationComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'app',([] as any[]),
      (null as any),(null as any),(null as any),View_ApplicationComponent_0,RenderType_ApplicationComponent)),
      i0.ɵdid(49152,(null as any),0,i2.ApplicationComponent,[i1.ActivatedRoute],(null as any),
          (null as any))],(null as any),(null as any));
}
export const ApplicationComponentNgFactory:i0.ComponentFactory<i2.ApplicationComponent> = i0.ɵccf('app',
    i2.ApplicationComponent,View_ApplicationComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvVmlsbWFudGFzL0RvY3VtZW50cy9WaXN1YWwgU3R1ZGlvIDIwMTcvUHJvamVjdHMvQW5ndWxhcjJDb3JlVGVtcGxhdGUvc3JjL1RlbXBsYXRlLkNsaWVudC9DbGllbnRBcHAvYXBwL2FwcGxpY2F0aW9uLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9WaWxtYW50YXMvRG9jdW1lbnRzL1Zpc3VhbCBTdHVkaW8gMjAxNy9Qcm9qZWN0cy9Bbmd1bGFyMkNvcmVUZW1wbGF0ZS9zcmMvVGVtcGxhdGUuQ2xpZW50L0NsaWVudEFwcC9hcHAvYXBwbGljYXRpb24uY29tcG9uZW50LnRzIiwibmc6Ly8vQzovVXNlcnMvVmlsbWFudGFzL0RvY3VtZW50cy9WaXN1YWwgU3R1ZGlvIDIwMTcvUHJvamVjdHMvQW5ndWxhcjJDb3JlVGVtcGxhdGUvc3JjL1RlbXBsYXRlLkNsaWVudC9DbGllbnRBcHAvYXBwL2FwcGxpY2F0aW9uLmNvbXBvbmVudC50cy5BcHBsaWNhdGlvbkNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvVmlsbWFudGFzL0RvY3VtZW50cy9WaXN1YWwgU3R1ZGlvIDIwMTcvUHJvamVjdHMvQW5ndWxhcjJDb3JlVGVtcGxhdGUvc3JjL1RlbXBsYXRlLkNsaWVudC9DbGllbnRBcHAvYXBwL2FwcGxpY2F0aW9uLmNvbXBvbmVudC50cy5BcHBsaWNhdGlvbkNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxyb3V0ZXItb3V0bGV0Pjwvcm91dGVyLW91dGxldD4iLCI8YXBwPjwvYXBwPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBO2FBQUE7c0NBQUE7VUFBQTtJQUFBOzs7O29CQ0FBO01BQUE7YUFBQTtVQUFBOzs7In0=
