/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../ClientApp/app/application.module';
import * as i2 from '../../../ClientApp/app/application.component';
import * as i3 from './admin/public/login/login.component.ngfactory';
import * as i4 from './admin/internal/users/users.component.ngfactory';
import * as i5 from './admin/internal/products/products.component.ngfactory';
import * as i6 from './admin/internal/admin.internal.component.ngfactory';
import * as i7 from './client/public/login/login.component.ngfactory';
import * as i8 from './application.component.ngfactory';
import * as i9 from '@angular/common';
import * as i10 from '@angular/platform-browser';
import * as i11 from '@angular/forms';
import * as i12 from '../../../ClientApp/app/admin/internal/users/users.service';
import * as i13 from '../../../ClientApp/app/admin/internal/users/users-resolver';
import * as i14 from '../../../ClientApp/app/admin/internal/products/products.service';
import * as i15 from '../../../ClientApp/app/admin/internal/products/products-resolver';
import * as i16 from '@angular/router';
import * as i17 from '../../../ClientApp/app/admin/public/login/login.component';
import * as i18 from '../../../ClientApp/app/admin/internal/users/users.component';
import * as i19 from '../../../ClientApp/app/admin/internal/products/products.component';
import * as i20 from '../../../ClientApp/app/admin/internal/admin.internal.component';
import * as i21 from '../../../ClientApp/app/client/public/login/login.component';
import * as i22 from '../../../ClientApp/app/admin/public/admin.public.module';
import * as i23 from '../../../ClientApp/app/admin/internal/admin.internal.module';
import * as i24 from '../../../ClientApp/app/admin/admin.module';
import * as i25 from '../../../ClientApp/app/client/public/client.public.module';
import * as i26 from '../../../ClientApp/app/client/internal/client.internal.module';
import * as i27 from '../../../ClientApp/app/client/client.module';
export const AppModuleNgFactory:i0.NgModuleFactory<i1.AppModule> = i0.ɵcmf(i1.AppModule,
    [i2.ApplicationComponent],(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i3.AdminLoginComponentNgFactory,i4.UserComponentNgFactory,i5.ProductComponentNgFactory,
              i6.AdminInternalComponentNgFactory,i7.ClientLoginComponentNgFactory,
              i8.ApplicationComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(5120,i0.LOCALE_ID,i0.ɵm,[[3,i0.LOCALE_ID]]),i0.ɵmpd(4608,i9.NgLocalization,
              i9.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(5120,i0.APP_ID,i0.ɵf,
              ([] as any[])),i0.ɵmpd(5120,i0.IterableDiffers,i0.ɵk,([] as any[])),
          i0.ɵmpd(5120,i0.KeyValueDiffers,i0.ɵl,([] as any[])),i0.ɵmpd(4608,i10.DomSanitizer,
              i10.ɵe,[i10.DOCUMENT]),i0.ɵmpd(6144,i0.Sanitizer,(null as any),[i10.DomSanitizer]),
          i0.ɵmpd(4608,i10.HAMMER_GESTURE_CONFIG,i10.HammerGestureConfig,([] as any[])),
          i0.ɵmpd(5120,i10.EVENT_MANAGER_PLUGINS,(p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
            return [new i10.ɵDomEventsPlugin(p0_0),new i10.ɵKeyEventsPlugin(p1_0),
                new i10.ɵHammerGesturesPlugin(p2_0,p2_1)];
          },[i10.DOCUMENT,i10.DOCUMENT,i10.DOCUMENT,i10.HAMMER_GESTURE_CONFIG]),i0.ɵmpd(4608,
              i10.EventManager,i10.EventManager,[i10.EVENT_MANAGER_PLUGINS,i0.NgZone]),
          i0.ɵmpd(135680,i10.ɵDomSharedStylesHost,i10.ɵDomSharedStylesHost,[i10.DOCUMENT]),
          i0.ɵmpd(4608,i10.ɵDomRendererFactory2,i10.ɵDomRendererFactory2,[i10.EventManager,
              i10.ɵDomSharedStylesHost]),i0.ɵmpd(6144,i0.RendererFactory2,(null as any),
              [i10.ɵDomRendererFactory2]),i0.ɵmpd(6144,i10.ɵSharedStylesHost,(null as any),
              [i10.ɵDomSharedStylesHost]),i0.ɵmpd(4608,i0.Testability,i0.Testability,
              [i0.NgZone]),i0.ɵmpd(4608,i10.Meta,i10.Meta,[i10.DOCUMENT]),i0.ɵmpd(4608,
              i10.Title,i10.Title,[i10.DOCUMENT]),i0.ɵmpd(4608,i11.ɵi,i11.ɵi,([] as any[])),
          i0.ɵmpd(4608,i11.FormBuilder,i11.FormBuilder,([] as any[])),i0.ɵmpd(4608,
              i12.UserService,i12.UserService,([] as any[])),i0.ɵmpd(4608,i13.UsersResolver,
              i13.UsersResolver,[i12.UserService]),i0.ɵmpd(4608,i14.ProductService,
              i14.ProductService,([] as any[])),i0.ɵmpd(4608,i15.ProductsResolver,
              i15.ProductsResolver,[i14.ProductService]),i0.ɵmpd(5120,i16.ActivatedRoute,
              i16.ɵf,[i16.Router]),i0.ɵmpd(4608,i16.NoPreloading,i16.NoPreloading,
              ([] as any[])),i0.ɵmpd(6144,i16.PreloadingStrategy,(null as any),[i16.NoPreloading]),
          i0.ɵmpd(135680,i16.RouterPreloader,i16.RouterPreloader,[i16.Router,i0.NgModuleFactoryLoader,
              i0.Compiler,i0.Injector,i16.PreloadingStrategy]),i0.ɵmpd(4608,i16.PreloadAllModules,
              i16.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,i16.ROUTER_INITIALIZER,
              i16.ɵi,[i16.ɵg]),i0.ɵmpd(5120,i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
            return [p0_0];
          },[i16.ROUTER_INITIALIZER]),i0.ɵmpd(512,i9.CommonModule,i9.CommonModule,
              ([] as any[])),i0.ɵmpd(1024,i0.ErrorHandler,i10.ɵa,([] as any[])),i0.ɵmpd(1024,
              i0.NgProbeToken,() => {
                return [i16.ɵb()];
              },([] as any[])),i0.ɵmpd(512,i16.ɵg,i16.ɵg,[i0.Injector]),i0.ɵmpd(1024,
              i0.APP_INITIALIZER,(p0_0:any,p0_1:any,p1_0:any) => {
                return [i10.ɵc(p0_0,p0_1),i16.ɵh(p1_0)];
              },[[2,i10.NgProbeToken],[2,i0.NgProbeToken],i16.ɵg]),i0.ɵmpd(512,i0.ApplicationInitStatus,
              i0.ApplicationInitStatus,[[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,
              i0.ɵe,[i0.NgZone,i0.ɵConsole,i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,
                  i0.ApplicationInitStatus]),i0.ɵmpd(2048,i0.ApplicationRef,(null as any),
              [i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,i0.ApplicationModule,[i0.ApplicationRef]),
          i0.ɵmpd(512,i10.BrowserModule,i10.BrowserModule,[[3,i10.BrowserModule]]),
          i0.ɵmpd(1024,i16.ɵa,i16.ɵd,[[3,i16.Router]]),i0.ɵmpd(512,i16.UrlSerializer,
              i16.DefaultUrlSerializer,([] as any[])),i0.ɵmpd(512,i16.ChildrenOutletContexts,
              i16.ChildrenOutletContexts,([] as any[])),i0.ɵmpd(256,i16.ROUTER_CONFIGURATION,
              {useHash:true,enableTracing:true},([] as any[])),i0.ɵmpd(1024,i9.LocationStrategy,
              i16.ɵc,[i9.PlatformLocation,[2,i9.APP_BASE_HREF],i16.ROUTER_CONFIGURATION]),
          i0.ɵmpd(512,i9.Location,i9.Location,[i9.LocationStrategy]),i0.ɵmpd(512,i0.Compiler,
              i0.Compiler,([] as any[])),i0.ɵmpd(512,i0.NgModuleFactoryLoader,i0.SystemJsNgModuleLoader,
              [i0.Compiler,[2,i0.SystemJsNgModuleLoaderConfig]]),i0.ɵmpd(1024,i16.ROUTES,
              () => {
                return [[{path:'login',component:i17.AdminLoginComponent}],[{path:'users',
                    component:i18.UserComponent,resolve:{users:i13.UsersResolver}},
                    {path:'products',component:i19.ProductComponent,resolve:{products:i15.ProductsResolver}}],
                    [{path:'internal',component:i20.AdminInternalComponent,loadChildren:'./internal/admin.internal.module#AdminInternalModule'},
                        {path:'public',loadChildren:'./public/admin.public.module#AdminPublicModule'}],
                    [{path:'login',component:i21.ClientLoginComponent}],[{path:'internal',
                        loadChildren:'./internal/client.internal.module#ClientInternalModule'},
                        {path:'public',loadChildren:'./public/client.public.module#ClientPublicModule'}],
                    [{path:'client',loadChildren:'./admin/admin.module#AdminModule'},
                        {path:'admin',loadChildren:'./client/client.module#ClientModule'}]];
              },([] as any[])),i0.ɵmpd(1024,i16.Router,i16.ɵe,[i0.ApplicationRef,i16.UrlSerializer,
              i16.ChildrenOutletContexts,i9.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i16.ROUTES,i16.ROUTER_CONFIGURATION,[2,i16.UrlHandlingStrategy],
              [2,i16.RouteReuseStrategy]]),i0.ɵmpd(512,i16.RouterModule,i16.RouterModule,
              [[2,i16.ɵa],[2,i16.Router]]),i0.ɵmpd(512,i11.ɵba,i11.ɵba,([] as any[])),
          i0.ɵmpd(512,i11.FormsModule,i11.FormsModule,([] as any[])),i0.ɵmpd(512,i11.ReactiveFormsModule,
              i11.ReactiveFormsModule,([] as any[])),i0.ɵmpd(512,i22.AdminPublicModule,
              i22.AdminPublicModule,([] as any[])),i0.ɵmpd(512,i23.AdminInternalModule,
              i23.AdminInternalModule,([] as any[])),i0.ɵmpd(512,i24.AdminModule,i24.AdminModule,
              ([] as any[])),i0.ɵmpd(512,i25.ClientPublicModule,i25.ClientPublicModule,
              ([] as any[])),i0.ɵmpd(512,i26.ClientInternalModule,i26.ClientInternalModule,
              ([] as any[])),i0.ɵmpd(512,i27.ClientModule,i27.ClientModule,([] as any[])),
          i0.ɵmpd(512,i1.AppModule,i1.AppModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvVmlsbWFudGFzL0RvY3VtZW50cy9WaXN1YWwgU3R1ZGlvIDIwMTcvUHJvamVjdHMvQW5ndWxhcjJDb3JlVGVtcGxhdGUvc3JjL1RlbXBsYXRlLkNsaWVudC9DbGllbnRBcHAvYXBwL2FwcGxpY2F0aW9uLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9WaWxtYW50YXMvRG9jdW1lbnRzL1Zpc3VhbCBTdHVkaW8gMjAxNy9Qcm9qZWN0cy9Bbmd1bGFyMkNvcmVUZW1wbGF0ZS9zcmMvVGVtcGxhdGUuQ2xpZW50L0NsaWVudEFwcC9hcHAvYXBwbGljYXRpb24ubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
