/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../../ClientApp/app/admin/public/admin.public.module';
import * as i2 from './login/login.component.ngfactory';
import * as i3 from '@angular/forms';
import * as i4 from '@angular/router';
import * as i5 from '../../../../../ClientApp/app/admin/public/login/login.component';
export const AdminPublicModuleNgFactory:i0.NgModuleFactory<i1.AdminPublicModule> = i0.ɵcmf(i1.AdminPublicModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.AdminLoginComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(4608,i3.ɵi,i3.ɵi,([] as any[])),i0.ɵmpd(4608,i3.FormBuilder,i3.FormBuilder,
              ([] as any[])),i0.ɵmpd(512,i3.ɵba,i3.ɵba,([] as any[])),i0.ɵmpd(512,
              i3.FormsModule,i3.FormsModule,([] as any[])),i0.ɵmpd(512,i3.ReactiveFormsModule,
              i3.ReactiveFormsModule,([] as any[])),i0.ɵmpd(512,i4.RouterModule,i4.RouterModule,
              [[2,i4.ɵa],[2,i4.Router]]),i0.ɵmpd(512,i1.AdminPublicModule,i1.AdminPublicModule,
              ([] as any[])),i0.ɵmpd(1024,i4.ROUTES,() => {
            return [[{path:'login',component:i5.AdminLoginComponent}]];
          },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvVmlsbWFudGFzL0RvY3VtZW50cy9WaXN1YWwgU3R1ZGlvIDIwMTcvUHJvamVjdHMvQW5ndWxhcjJDb3JlVGVtcGxhdGUvc3JjL1RlbXBsYXRlLkNsaWVudC9DbGllbnRBcHAvYXBwL2FkbWluL3B1YmxpYy9hZG1pbi5wdWJsaWMubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL1ZpbG1hbnRhcy9Eb2N1bWVudHMvVmlzdWFsIFN0dWRpbyAyMDE3L1Byb2plY3RzL0FuZ3VsYXIyQ29yZVRlbXBsYXRlL3NyYy9UZW1wbGF0ZS5DbGllbnQvQ2xpZW50QXBwL2FwcC9hZG1pbi9wdWJsaWMvYWRtaW4ucHVibGljLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
