/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../../ClientApp/app/admin/internal/admin.internal.module';
import * as i2 from './users/users.component.ngfactory';
import * as i3 from './products/products.component.ngfactory';
import * as i4 from '@angular/common';
import * as i5 from '../../../../../ClientApp/app/admin/internal/users/users.service';
import * as i6 from '../../../../../ClientApp/app/admin/internal/users/users-resolver';
import * as i7 from '../../../../../ClientApp/app/admin/internal/products/products.service';
import * as i8 from '../../../../../ClientApp/app/admin/internal/products/products-resolver';
import * as i9 from '@angular/router';
import * as i10 from '../../../../../ClientApp/app/admin/internal/users/users.component';
import * as i11 from '../../../../../ClientApp/app/admin/internal/products/products.component';
export const AdminInternalModuleNgFactory:i0.NgModuleFactory<i1.AdminInternalModule> = i0.ɵcmf(i1.AdminInternalModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.UserComponentNgFactory,i3.ProductComponentNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(4608,i4.NgLocalization,i4.NgLocaleLocalization,
          [i0.LOCALE_ID]),i0.ɵmpd(4608,i5.UserService,i5.UserService,([] as any[])),
          i0.ɵmpd(4608,i6.UsersResolver,i6.UsersResolver,[i5.UserService]),i0.ɵmpd(4608,
              i7.ProductService,i7.ProductService,([] as any[])),i0.ɵmpd(4608,i8.ProductsResolver,
              i8.ProductsResolver,[i7.ProductService]),i0.ɵmpd(512,i9.RouterModule,
              i9.RouterModule,[[2,i9.ɵa],[2,i9.Router]]),i0.ɵmpd(512,i4.CommonModule,
              i4.CommonModule,([] as any[])),i0.ɵmpd(512,i1.AdminInternalModule,i1.AdminInternalModule,
              ([] as any[])),i0.ɵmpd(1024,i9.ROUTES,() => {
            return [[{path:'users',component:i10.UserComponent,resolve:{users:i6.UsersResolver}},
                {path:'products',component:i11.ProductComponent,resolve:{products:i8.ProductsResolver}}]];
          },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvVmlsbWFudGFzL0RvY3VtZW50cy9WaXN1YWwgU3R1ZGlvIDIwMTcvUHJvamVjdHMvQW5ndWxhcjJDb3JlVGVtcGxhdGUvc3JjL1RlbXBsYXRlLkNsaWVudC9DbGllbnRBcHAvYXBwL2FkbWluL2ludGVybmFsL2FkbWluLmludGVybmFsLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9WaWxtYW50YXMvRG9jdW1lbnRzL1Zpc3VhbCBTdHVkaW8gMjAxNy9Qcm9qZWN0cy9Bbmd1bGFyMkNvcmVUZW1wbGF0ZS9zcmMvVGVtcGxhdGUuQ2xpZW50L0NsaWVudEFwcC9hcHAvYWRtaW4vaW50ZXJuYWwvYWRtaW4uaW50ZXJuYWwubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
