/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './navbar/navbar.component.ngfactory';
import * as i2 from '../../../../../ClientApp/app/admin/internal/navbar/navbar.component';
import * as i3 from '@angular/router';
import * as i4 from '../../../../../ClientApp/app/admin/internal/admin.internal.component';
const styles_AdminInternalComponent:any[] = ([] as any[]);
export const RenderType_AdminInternalComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_AdminInternalComponent,data:{}});
export function View_AdminInternalComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),13,'div',[['class',
      '']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
          1,'nav-bar',([] as any[]),(null as any),(null as any),(null as any),i1.View_NavBarComponent_0,
          i1.RenderType_NavBarComponent)),i0.ɵdid(49152,(null as any),0,i2.NavBarComponent,
          ([] as any[]),(null as any),(null as any)),(_l()(),i0.ɵted((null as any),
          ['\n    '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),7,'div',[['class',
          'container']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),i0.ɵeld(0,(null as any),
          (null as any),4,'div',[['class','panel']],(null as any),(null as any),(null as any),
          (null as any),(null as any))),(_l()(),i0.ɵted((null as any),['\n            '])),
      (_l()(),i0.ɵeld(16777216,(null as any),(null as any),1,'router-outlet',([] as any[]),
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      i0.ɵdid(212992,(null as any),0,i3.RouterOutlet,[i3.ChildrenOutletContexts,i0.ViewContainerRef,
          i0.ComponentFactoryResolver,[8,(null as any)],i0.ChangeDetectorRef],(null as any),
          (null as any)),(_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),i0.ɵted((null as any),
          ['\n    '])),(_l()(),i0.ɵted((null as any),['\n']))],(_ck,_v) => {
    _ck(_v,10,0);
  },(null as any));
}
export function View_AdminInternalComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'ng-component',
      ([] as any[]),(null as any),(null as any),(null as any),View_AdminInternalComponent_0,
      RenderType_AdminInternalComponent)),i0.ɵdid(49152,(null as any),0,i4.AdminInternalComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const AdminInternalComponentNgFactory:i0.ComponentFactory<i4.AdminInternalComponent> = i0.ɵccf('ng-component',
    i4.AdminInternalComponent,View_AdminInternalComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvVmlsbWFudGFzL0RvY3VtZW50cy9WaXN1YWwgU3R1ZGlvIDIwMTcvUHJvamVjdHMvQW5ndWxhcjJDb3JlVGVtcGxhdGUvc3JjL1RlbXBsYXRlLkNsaWVudC9DbGllbnRBcHAvYXBwL2FkbWluL2ludGVybmFsL2FkbWluLmludGVybmFsLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9WaWxtYW50YXMvRG9jdW1lbnRzL1Zpc3VhbCBTdHVkaW8gMjAxNy9Qcm9qZWN0cy9Bbmd1bGFyMkNvcmVUZW1wbGF0ZS9zcmMvVGVtcGxhdGUuQ2xpZW50L0NsaWVudEFwcC9hcHAvYWRtaW4vaW50ZXJuYWwvYWRtaW4uaW50ZXJuYWwuY29tcG9uZW50LnRzIiwibmc6Ly8vQzovVXNlcnMvVmlsbWFudGFzL0RvY3VtZW50cy9WaXN1YWwgU3R1ZGlvIDIwMTcvUHJvamVjdHMvQW5ndWxhcjJDb3JlVGVtcGxhdGUvc3JjL1RlbXBsYXRlLkNsaWVudC9DbGllbnRBcHAvYXBwL2FkbWluL2ludGVybmFsL2FkbWluLmludGVybmFsLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvVmlsbWFudGFzL0RvY3VtZW50cy9WaXN1YWwgU3R1ZGlvIDIwMTcvUHJvamVjdHMvQW5ndWxhcjJDb3JlVGVtcGxhdGUvc3JjL1RlbXBsYXRlLkNsaWVudC9DbGllbnRBcHAvYXBwL2FkbWluL2ludGVybmFsL2FkbWluLmludGVybmFsLmNvbXBvbmVudC50cy5BZG1pbkludGVybmFsQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGRpdiBjbGFzcz1cIlwiPlxyXG4gICAgPG5hdi1iYXI+PC9uYXYtYmFyPlxyXG4gICAgPGRpdiBjbGFzcz1cImNvbnRhaW5lclwiPlxyXG4gICAgICAgIDxkaXYgY2xhc3M9XCJwYW5lbFwiPlxyXG4gICAgICAgICAgICA8cm91dGVyLW91dGxldD48L3JvdXRlci1vdXRsZXQ+XHJcbiAgICAgICAgPC9kaXY+XHJcbiAgICA8L2Rpdj5cclxuPC9kaXY+IiwiPG5nLWNvbXBvbmVudD48L25nLWNvbXBvbmVudD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBO01BQWMsMkNBQ1Y7VUFBQTt1Q0FBQSxVQUFBO1VBQUEsMkNBQW1CO1VBQUEsYUFDbkI7VUFBQTtNQUF1QiwrQ0FDbkI7VUFBQTtVQUFBLDhCQUFtQjtNQUNmO1VBQUE7YUFBQTtzQ0FBQTtVQUFBLGVBQStCLCtDQUM3QjtVQUFBLGFBQ0o7SUFGRTs7OztvQkNKWjtNQUFBO3VDQUFBLFVBQUE7TUFBQTs7OyJ9
